server.port=${PORT:8080}


spring.datasource.url=postgresql://food_order_database_user:FmmNFNpgbVhIY11g7vjXxDrOYOaduKFE@dpg-d71n395m5p6s739tck60-a.oregon-postgres.render.com/food_order_database
spring.datasource.username=food_order_database_user
spring.datasource.password=FmmNFNpgbVhIY11g7vjXxDrOYOaduKFE
spring.datasource.driver-class-name=org.postgresql.Driver

cloudinary.cloud_name=dj2zcuqzt
cloudinary.api_key=861942856239387
cloudinary.api_secret=8SC-tRKlGDYvDT8Uc-QkCbimAUs

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




